FROM python:3.11.3-bullseye
RUN apt update && apt upgrade -y
RUN apt install -y git
RUN pip install --upgrade pip
RUN git clone https://github.com/fgg89/market_snitcher_bot.git /opt/market_snitcher_bot
RUN cd /opt/market_snitcher_bot && pip install -Ur requirements.txt

# FROM python:alpine3.18
# RUN apk update && apk upgrade
# RUN apk add git build-base libxml2-dev libxslt-dev libffi-dev
# RUN pip install --upgrade pip
# TODO: install numpy with pip
# RUN git clone https://github.com/fgg89/market_snitcher_bot.git /opt/market_snitcher_bot
# RUN cd /opt/market_snitcher_bot && pip install -Ur requirements.txt